ch/urls.py
# author: Shchapaniak Andrei

from django.urls import path

import ch.views as views

app_name = 'ch'

urlpatterns = [
    path('', views.IndexView.as_view(), name='home-page'),
    path('api/get_conf_state/<slug:slug>', views.PurchaseGetState.as_view(), name='api_get-conf-state-slug'),
    path('api/refund_money/<slug:slug>', views.PurchaseRefundMoney.as_view(), name='api_get-refund-money-slug'),
    path('api/get_all_states_bucket', views.PurchaseGetStateConfsUser.as_view(), name='api_get-all-states-bucket'),
    path('api/change_capacity_bucket/<slug:slug>', views.PurchaseManipulateBucket.as_view(), name='api_change-capacity-bucket-slug'),
    path('api/buy_confs', views.PurchaseBuyConfs.as_view(), name='api_buy-confs'),
    path('search', views.SearchView.as_view(), name='search-page'),
    path('<slug>/bucket', views.PurchasesView.as_view(), name='bucket-page'),
]

conference_hub/urls.py
# author: Shchapaniak Andrei

from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views

from rest_framework_simplejwt.views import (
    TokenRefreshView,
)


urlpatterns = [
    path('admin/', admin.site.urls),

    path('api/', views.getRoutes),
    path('api/token/', views.MyTokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),

    # path('', include('ch.urls')),
    path('users/', include('users.urls')),
    path('conferences/', include('conferences.urls')),
    path('ch/', include('ch.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'conference_hub.views.error_404_view'

conferences/urls.py
# author: Shchapaniak Andrei
# author: Khrystsiuk Dziyana

from django.urls import path
from conferences import views

from rest_framework import routers

app_name = 'conferences'

urlpatterns = [
    path('', views.ConferencesListView.as_view(), name='conferences-page'),
    path('api/get_conf/<slug:slug>', views.ConferenceGetOneAPI.as_view(), name='api_get-one-conf'),
    path('api/get_all_confs', views.ConferenceGetAllAPI.as_view(), name='api_get-all-confs'),
    path('api/manipulate_conf/<slug:slug>', views.ConferenceOrganizationManipulateAPI.as_view(), name='api_manipulate-conf'),
    path('api/get_events/<slug:slug>', views.ConferenceGetEventsAPI.as_view(), name='api_get_events-conf'),
    path('api/create_event/<slug:slug>', views.ConferenceCreateEventAPI.as_view(), name='api_create_event-conf'),
    path('api/delete_event/<slug:slug>', views.ConferenceDeleteEventAPI.as_view(), name='api_delete_event-conf'),
    path('api/update_event/<slug:slug>', views.ConferenceUpdateEventAPI.as_view(), name='api_update_event-conf'),

    path('<slug:username>/display', views.DisplayConferenceView.as_view(), name='conf_display-page'),
    path('<slug:username>/my_lectures', views.UserEventsView.as_view(), name='user_lectures-page'),
    path('<slug:username>/create', views.CreateConferenceView.as_view(), name='conf_create-page'),
    path('<slug:username>/edit/<slug:slug>', views.EditConferenceView.as_view(), name='conf_edit-page'),
    path('delete/<slug:slug>', views.DeleteConferenceView.as_view(), name='conf_delete-page'),
    path('<slug:slug>', views.ConferenceInfoView.as_view(), name='conf_detail-page'),
    path('<slug:slug>/event/<slug:username>/create', views.CreateEventView.as_view(), name='event_create-page'),
    path('<slug:slug>/event/<slug:username>/edit/<int:pk>', views.EditEventView.as_view(), name='event_edit-page'),
    path('<slug:slug>/event/<slug:username>/delete/<int:pk>', views.DeleteEventView.as_view(), name='event_delete-page'),
    path('<slug:slug>/event/<int:pk>', views.EventInfoView.as_view(), name='event_detail-page'),
]

users/urls.py
# author: Shchapaniak Andrei
# author: Skuratovich Aliaksandr

from django.contrib.auth import views as auth_views
from django.urls import path, include
from users import views

from rest_framework import routers

router = routers.DefaultRouter()
router.register(r'users_list', views.ConferenceUserListAPIView, 'api_users-list')
router.register(r'signup-researcher', views.ResearcherSignupAPIView, 'api_signup-researcher')
router.register(r'signup-organization', views.OrganizationSignupAPIView, 'api_signup-organization')
router.register('', views.ProfileAPIView, 'api_profile')

app_name = 'users'

urlpatterns = [
    # path('', views.ConferenceUserListView.as_view(), name='users-models'),  # move to routers
    path('api/get_users_all', views.ConferenceUserGetUsers.as_view(), name='api_get-users-all'),
    path('api/get_users_researchers', views.ConferenceUserGetResearchers.as_view(), name='api_get-users-researchers'),
    path('api/get_users_organizations', views.ConferenceUserGetOrganizations.as_view(), name='api_get-users-organizations'),
    path('api/manipulate_info_user', views.ConferenceUserGetInfo.as_view(), name='api_get-info-user'),
    path('api/login', views.ConferenceUserSigninAPIView.as_view(), name='api-login-view'),
    path('api/get_invite_context', views.InviteAPIView.as_view(), name='api-invite-view'),
    path('api/', include(router.urls)),  # move to routers

    path('invites', views.InviteView.as_view(), name='invites-page'),
    path('login', views.ConferenceUserSigninView.as_view(), name='login-page'),
    path('logout', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout-page'),

    path('signup', views.ConferenceUserSignupView.as_view(), name='signup-page'),

    path('signup/researcher', views.ResearcherSignupView.as_view(), name='signup_researcher-page'),
    path('signup/organization', views.OrganizationSignupView.as_view(), name='signup_organization-page'),

    path('<slug>/edit_profile', views.ProfileUpdateView.as_view(), name='profile_update-page'),
    path('<slug>/password_change', views.ProfileChangePasswordView.as_view(), name='password_change-page'),
    path('<slug>/account_delete', views.AccountDeleteView.as_view(), name='account_delete-page'),

    path('<slug>/organizations', views.OrganizationsView.as_view(), name='organizations-page'),
    path('<slug>/employees', views.EmployeesView.as_view(), name='employees-page'),

    path('<slug>', views.ProfileView.as_view(), name='profile-page'),
]

templates/navbar/navbar-left.html
{% load static %}
{% load compress %}

{% compress css %}
    <link rel="stylesheet" type="text/x-scss" href="{% static 'css/ch/style.scss' %}">
{% endcompress %}

<form class="navbar-form navbar-left" method="get" action="{% url 'ch:search-page' %}">
   <input type="hidden" name="type" value="researchers"/>
    <div class="input-group">
        <input type="text" class="form-control transparent-input" placeholder="Search" aria-label="Search" name="q"
               id="searched">
        <div class="input-group-btn">
            <button class="btn btn-default transparent-input" type="submit">
                <b>?</b>
                {#                    <i class="glyphicon glyphicon-search" ></i>#}
            </button>
        </div>
    </div>
</form>

<div class="navbar-nav mr-auto">

    {% if user.is_authenticated %}
        {% include 'users/autologout.html' %}

         <div class="nav-item parent">
            <svg xmlns="http://www.w3.org/2000/svg" width="20" height="16"
                 fill="currentColor" class="bi bi-clock child" viewBox="0 0 16 16">
                <path d="M8 3.5a.5.5 0 0 0-1 0V9a.5.5 0 0 0 .252.434l3.5 2a.5.5 0 0 0 .496-.868L8 8.71V3.5z"/>
                <path d="M8 16A8 8 0 1 0 8 0a8 8 0 0 0 0 16zm7-8A7 7 0 1 1 1 8a7 7 0 0 1 14 0z"/>
            </svg>
            <a class="nav-item nav-link child timer" id="timer"></a>
        </div>

        <script src="{% static 'js/autologout.js' %}" type="text/javascript"></script>
    {% endif %}
</div>

templates/navbar/navbar-right.html
{% load static %}
{% load compress %}

{#<link type="text/x-scss" href="{% static 'css/dropdown.scss' %}" rel="stylesheet" media="screen">#}

{#<script src="{% static 'static/js/dropdown.js' %}"></script>#}

<div class="navbar-nav navbar-inverse">
    <style>
        .dropdown-item {
            color: black !important;
            background: transparent !important;
        }
        .dropdown-item a{
            color: black !important;
            background: transparent !important;
        }
        .dropdown-item:hover{
            color: black !important;
            background: rgba(0, 0, 0, 0.04) !important;
            border-color: rgba(0, 0, 0, 0.04) !important;
        }
        .dropdown-item:focus{
            color: white !important;
            background: rgba(0, 0, 0, 0.47) !important;
            border-color: rgba(0, 0, 0, 0.47) !important;
        }
    </style>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDarkDropdown"
            aria-controls="navbarNavDarkDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>


    {#    dropdown toolbar for user & settings#}
    <div class="collapse navbar-collapse" id="navbarNavDarkDropdown">
        {% if user.is_superuser %}
            <li class="nav-item dropdown">
                <a class="nav-link " data-toggle="dropdown" role="button"
                   id="navbarDropdownMenuLink" aria-haspopup="true"
                   aria-expanded="false">
                   <img class="rounded-circle siteheader-img" src="{{ user.profile.image.url  }}">
                </a>

                <div class="dropdown-menu" style="right: 0; left: auto; border-radius: 10px;"
                     aria-labelledby="navbarDropdownMenuLink">
                    <a class="dropdown-item" href="{% url 'users:profile-page' user.username %}">Profile</a>
                    <a class="dropdown-item" href="{% url 'users:logout-page' %}">Log Out</a>
                </div>
            </li>
            <div style="margin-left: 20px;">ADMIN</div>
        {% elif user.is_authenticated %}
            {% if user.status %}
                <div class="status">
                    <span class="dot" style="  background-color: greenyellow;"></span>
                    ACTIVE
                </div>
            {% else %}
                <div class="status">
                    <span class="dot" style="background-color: red;"></span>
                    INACTIVE
                </div>
            {% endif %}
            <li class="nav-item dropdown">
                <a class="nav-link " data-toggle="dropdown" role="button"
                   id="navbarDropdownMenuLink" aria-haspopup="true"
                   aria-expanded="false">
                   <img class="rounded-circle siteheader-img" src="{{ user.profile.image.url  }}">
                </a>

                <div class="dropdown-menu" style="right: 0; left: auto; border-radius: 10px;"
                     aria-labelledby="navbarDropdownMenuLink">
                    <a class="dropdown-item" href="{% url 'users:profile-page' user.username %}">Profile</a>
                    <a class="dropdown-item" href="{% url 'users:profile_update-page' user.username %}">Edit Profile</a>
                    <div class="dropdown-divider"></div>
                    {% if user.is_researcher %}
                        <a class="dropdown-item" href="{% url 'conferences:conf_display-page' user.username %}">My conferences</a>
                        <a class="dropdown-item" href="{% url 'conferences:user_lectures-page' user.username %}">My lectures</a>
                        <a class="dropdown-item" href="{% url 'users:organizations-page' user.username %}">My organizations</a>
                        <a class="dropdown-item" href="{% url 'users:invites-page' %}">Membership invites</a>
                    {% elif user.is_organization %}
                        {# TODO 41: add list of members with crud functionality#}
                        <a class="dropdown-item" href="{% url 'users:employees-page' user.username %}">Members</a>
                        <a class="dropdown-item" href="{% url 'users:invites-page' %}">Invites</a>
                        {# TODO 40: add list with organization's conferences with a crud functionality#}
                        <a class="dropdown-item" href="{% url 'conferences:conf_display-page' user.username %}">Conferences</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="{% url 'conferences:conf_create-page' user.username %}">New Conference</a>
                    {% else %}
                    {% endif %}
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item">{{ user.balance }}</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="{% url 'users:logout-page' %}">Log Out</a>
                </div>
            </li>

            {#    TODO 43: if bucket is empty, dont't show it #}
            {#    TODO 44: add a possibility to pay for a conference #}
            {% if user.is_researcher %}
                <div class="navbar-nav mr-auto">
                    <a class="nav-item nav-link" href="{% url 'ch:bucket-page' user.username %}">Bucket</a>
                </div>

            {#    TODO 45: add notifications (e-mail, browser)#}
            <div class="navbar-nav mr-auto" onclick="manage_notification_bar()">
                <a class="nav-item nav-link">Lecture invites <sup id="cnt_invites">{{ user.researcher.get_number_invites }}</sup></a>
            </div>
            {% endif %}

        {% else %}
            <a class="nav-item nav-link" href="{% url 'users:login-page' %}">Sign In</a>
            <a class="nav-item nav-link" href="{% url 'users:signup-page' %}">Sign Up</a>
        {% endif %}
    </div>

</div>

templates/navbar/navbar.html
{% load static %}

<nav class="navbar bg-navbar navbar-expand-md navbar-position" style="width: 100% !important;">
        <div class="navbar-header">
            <a class="navbar-brand" href="{% url 'ch:home-page' %}"><b>C</b>onference <b>H</b>ub</a>
        </div>

        <nav class="collapse navbar-collapse" id="navbarToggle" id="navbarNavDarkDropdown">
            <!-- Navbar Left side -->
            {% include "navbar/navbar-left.html" %}
            <!-- Navbar Right side -->
            {% include "navbar/navbar-right.html" %}
        </nav>
</nav>