ch/urls.py
# author: Shchapaniak Andrei

from django.urls import path

import ch.views as views

app_name = 'ch'

urlpatterns = [
    path('', views.IndexView.as_view(), name='home-page'),
    path('api/get_conf_state/<slug:slug>', views.PurchaseGetState.as_view(), name='api_get-conf-state-slug'),
    path('api/refund_money/<slug:slug>', views.PurchaseRefundMoney.as_view(), name='api_get-refund-money-slug'),
    path('api/get_all_states_bucket', views.PurchaseGetStateConfsUser.as_view(), name='api_get-all-states-bucket'),
    path('api/change_capacity_bucket/<slug:slug>', views.PurchaseManipulateBucket.as_view(), name='api_change-capacity-bucket-slug'),
    path('api/buy_confs', views.PurchaseBuyConfs.as_view(), name='api_buy-confs'),
    path('search', views.SearchView.as_view(), name='search-page'),
    path('<slug>/bucket', views.PurchasesView.as_view(), name='bucket-page'),
]

conference_hub/urls.py
# author: Shchapaniak Andrei

from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views

from rest_framework_simplejwt.views import (
    TokenRefreshView,
)


urlpatterns = [
    path('admin/', admin.site.urls),

    path('api/', views.getRoutes),
    path('api/token/', views.MyTokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),

    # path('', include('ch.urls')),
    path('users/', include('users.urls')),
    path('conferences/', include('conferences.urls')),
    path('ch/', include('ch.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'conference_hub.views.error_404_view'

conferences/urls.py
# author: Shchapaniak Andrei
# author: Khrystsiuk Dziyana

from django.urls import path
from conferences import views

from rest_framework import routers

app_name = 'conferences'

urlpatterns = [
    path('', views.ConferencesListView.as_view(), name='conferences-page'),
    path('api/get_conf/<slug:slug>', views.ConferenceGetOneAPI.as_view(), name='api_get-one-conf'),
    path('api/get_all_confs', views.ConferenceGetAllAPI.as_view(), name='api_get-all-confs'),
    path('api/manipulate_conf/<slug:slug>', views.ConferenceOrganizationManipulateAPI.as_view(), name='api_manipulate-conf'),
    path('api/get_events/<slug:slug>', views.ConferenceGetEventsAPI.as_view(), name='api_get_events-conf'),
    path('api/create_event/<slug:slug>', views.ConferenceCreateEventAPI.as_view(), name='api_create_event-conf'),
    path('api/delete_event/<slug:slug>', views.ConferenceDeleteEventAPI.as_view(), name='api_delete_event-conf'),
    path('api/update_event/<slug:slug>', views.ConferenceUpdateEventAPI.as_view(), name='api_update_event-conf'),

    path('<slug:username>/display', views.DisplayConferenceView.as_view(), name='conf_display-page'),
    path('<slug:username>/my_lectures', views.UserEventsView.as_view(), name='user_lectures-page'),
    path('<slug:username>/create', views.CreateConferenceView.as_view(), name='conf_create-page'),
    path('<slug:username>/edit/<slug:slug>', views.EditConferenceView.as_view(), name='conf_edit-page'),
    path('delete/<slug:slug>', views.DeleteConferenceView.as_view(), name='conf_delete-page'),
    path('<slug:slug>', views.ConferenceInfoView.as_view(), name='conf_detail-page'),
    path('<slug:slug>/event/<slug:username>/create', views.CreateEventView.as_view(), name='event_create-page'),
    path('<slug:slug>/event/<slug:username>/edit/<int:pk>', views.EditEventView.as_view(), name='event_edit-page'),
    path('<slug:slug>/event/<slug:username>/delete/<int:pk>', views.DeleteEventView.as_view(), name='event_delete-page'),
    path('<slug:slug>/event/<int:pk>', views.EventInfoView.as_view(), name='event_detail-page'),
]

users/urls.py
# author: Shchapaniak Andrei
# author: Skuratovich Aliaksandr

from django.contrib.auth import views as auth_views
from django.urls import path, include
from users import views

from rest_framework import routers

router = routers.DefaultRouter()
router.register(r'users_list', views.ConferenceUserListAPIView, 'api_users-list')
router.register(r'signup-researcher', views.ResearcherSignupAPIView, 'api_signup-researcher')
router.register(r'signup-organization', views.OrganizationSignupAPIView, 'api_signup-organization')
router.register('', views.ProfileAPIView, 'api_profile')

app_name = 'users'

urlpatterns = [
    # path('', views.ConferenceUserListView.as_view(), name='users-models'),  # move to routers
    path('api/get_users_all', views.ConferenceUserGetUsers.as_view(), name='api_get-users-all'),
    path('api/get_users_researchers', views.ConferenceUserGetResearchers.as_view(), name='api_get-users-researchers'),
    path('api/get_users_organizations', views.ConferenceUserGetOrganizations.as_view(), name='api_get-users-organizations'),
    path('api/manipulate_info_user', views.ConferenceUserGetInfo.as_view(), name='api_get-info-user'),
    path('api/login', views.ConferenceUserSigninAPIView.as_view(), name='api-login-view'),
    path('api/get_invite_context', views.InviteAPIView.as_view(), name='api-invite-view'),
    path('api/', include(router.urls)),  # move to routers

    path('invites', views.InviteView.as_view(), name='invites-page'),
    path('login', views.ConferenceUserSigninView.as_view(), name='login-page'),
    path('logout', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout-page'),

    path('signup', views.ConferenceUserSignupView.as_view(), name='signup-page'),

    path('signup/researcher', views.ResearcherSignupView.as_view(), name='signup_researcher-page'),
    path('signup/organization', views.OrganizationSignupView.as_view(), name='signup_organization-page'),

    path('<slug>/edit_profile', views.ProfileUpdateView.as_view(), name='profile_update-page'),
    path('<slug>/password_change', views.ProfileChangePasswordView.as_view(), name='password_change-page'),
    path('<slug>/account_delete', views.AccountDeleteView.as_view(), name='account_delete-page'),

    path('<slug>/organizations', views.OrganizationsView.as_view(), name='organizations-page'),
    path('<slug>/employees', views.EmployeesView.as_view(), name='employees-page'),

    path('<slug>', views.ProfileView.as_view(), name='profile-page'),
]

ch/forms/conference.py
from django import forms
from django.db import transaction
from django.forms import ModelForm

from ch.models import Conference, Event


class CreateConferenceForm(ModelForm):
    date_from = forms.DateField(
        input_formats=[f'%d.%m.%Y'],
        widget=forms.DateInput(
            attrs={
                'placeholder': 'dd.mm.yyyy',
            }
        )
    )

    date_to = forms.DateField(
        input_formats=[f'%d.%m.%Y'],
        widget=forms.DateInput(
            attrs={
                'placeholder': 'dd.mm.yyyy',
            }
        )
    )

    class Meta:
        model = Conference
        fields = ["name", "date_from", "date_to", "address", "price"]

    @transaction.atomic
    def save(self):
        # first, create a user
        conf = super().save(commit=False)
        conf.save()
        return conf


class CreateEventForm(ModelForm):
    date_time = forms.DateTimeField(
        input_formats=[f'%d.%m.%Y %H:%M'],
        widget=forms.DateInput(
            attrs={
                'placeholder': 'dd.mm.yyyy hh:mm',
            }
        )
    )

    class Meta:
        model = Event
        fields = '__all__'

    # def __init__(self, *args, **kwargs):
    # 	conf = kwargs.pop('conf','')
    # 	super().__init__(*args, **kwargs)
    # 	self.fields['conference']=forms.ModelChoiceField(queryset=Conference.objects.filter(pk=conf))

    @transaction.atomic
    def save(self):
        # first, create a user
        event = super().save(commit=False)
        event.save()
        return event

conferences/views/conferences.py
# author: Khrystsiuk Dziyana
# author: Shchapaniak Andrei

from django.contrib.auth.decorators import login_required
import datetime
from django.urls import reverse, reverse_lazy
from django.views import generic
from django.utils import timezone
from conferences.models import ConferenceModel
from conferences import forms as conf_forms
from users import models as u_models
from conferences import models as conf_models
from django.shortcuts import redirect, get_object_or_404
from conference_hub.utils.message_wrapper import MessageMixin
from django.contrib.auth.mixins import PermissionRequiredMixin, LoginRequiredMixin
import conferences.serializers as sers
from rest_framework import viewsets, generics
from rest_framework.response import Response
from rest_framework.views import APIView
from rest_framework.permissions import IsAuthenticated
from rest_framework.parsers import FileUploadParser
from rest_framework import status
from datetime import date

import logging

logger = logging.getLogger(__name__)


class ConferenceGetOneAPI(APIView):
    queryset = conf_models.ConferenceModel
    serializer_class = sers.ConferenceSerializerSlug
    lookup_field = 'slug'

    def get(self, request, *args, **kwargs):
        content = {}
        conf = conf_models.ConferenceModel.objects.get(slug=kwargs['slug'])
        content['conf'] = sers.ConferenceSerializer(conf).data

        logger.debug(f'\n\n{content["conf"]}\n\n')

        return Response(content, status=status.HTTP_200_OK)


class ConferenceGetAllAPI(generics.RetrieveAPIView):
    queryset = conf_models.ConferenceModel
    serializer_class = sers.ConferenceSerializer

    def get(self, request, *args, **kwargs):
        confs = conf_models.ConferenceModel.objects.all()
        content = sers.ConferenceSerializer(confs, many=True).data
        return Response(content, status=status.HTTP_200_OK)


class ConferenceCreateEventAPI(APIView):

    def post(self, request, *args, **kwargs):
        data = request.data['data']
        data['duration'] = datetime.timedelta(seconds=int(data['duration']))
        conference = ConferenceModel.objects.get(slug=kwargs['slug'])

        new_event = conf_models.EventModel(
            conference=conference,
            **{k: data[k] for k in [
                "name",
                "date_time",
                "date_time_end",
                "duration",
                "location",
                "description",
                "type",
            ]}
        )
        new_event.save()

        match new_event.type:
            case "lecture":
                nm = conf_models.LectureModel(
                    event=new_event,
                    # menu=data['menu']
                )
                nm.save()
            case "lunch":
                nm = conf_models.LunchModel(
                    event=new_event,
                    price=int(data['price'])
                )
                nm.save()

        return Response(status=status.HTTP_201_CREATED)


class ConferenceUpdateEventAPI(APIView):

    def post(self, request, *args, **kwargs):
        data = request.data['data']
        event_id = data['event_id']
        conference = ConferenceModel.objects.get(slug=kwargs['slug'])

        event = conf_models.EventModel.objects.get(
            conference=conference,
            event_id=event_id
        )
        logger.debug( 'OLD VALUES:' + '\n\t '.join([f'{k}: {v}' for k, v in data.items()]) )

        for k, v in data.items():
            if k in ['name', 'description', 'data_time', 'date_time_end'] and getattr(event, k) != v:
                setattr(event, k, v)
                logger.debug(f'------ updating {k} -> {v}')

        event.save()
        logger.debug( 'NEW VALUES:' + '\n\t '.join([f'{k}: {v}' for k, v in data.items()]) )

        return Response(status=status.HTTP_201_CREATED)


class ConferenceDeleteEventAPI(APIView):

    def post(self, request, *args, **kwargs):
        event_id = request.data['data']['event_id']
        conference = ConferenceModel.objects.get(slug=kwargs['slug'])

        event = conf_models.EventModel.objects.get(
            conference=conference,
            event_id=event_id
        )
        logger.debug('event to delete: ', event)
        event.delete()

        return Response(status=status.HTTP_201_CREATED)


class ConferenceGetEventsAPI(APIView):

    def get(self, request, *args, **kwargs):
        content = {}
        logger.debug(
            list(kwargs.items())
        )
        conf = conf_models.ConferenceModel.objects.get(slug=kwargs['slug'])
        logger.debug(f'conference: {conf}')
        try:
            events = conf_models.EventModel.objects.filter(conference=conf)
        except conf_models.EventModel.DoesNotExist:
            events = [{
            }]

        content['events'] = list(map(lambda x: sers.EventSerializer(x).data, events))

        def improve_event(event):
            dd = {"lunch": conf_models.LunchModel, }
            if event['type'] in dd.keys():
                event['price'] = int(
                    dd[event['type']].objects.get(event__pk=event['event_id'], event__conference=conf).price.amount)
            return event

        content['events'] = list(map(lambda x: improve_event(x), content['events']))

        return Response(content, status=status.HTTP_200_OK)


class ConferenceOrganizationManipulateAPI(APIView):
    queryset = conf_models.ConferenceModel
    serializer_class = sers.ConferenceSerializerSlug
    permission_classes = (IsAuthenticated,)
    lookup_field = 'slug'

    def get(self, request, *args, **kwargs):
        content = {}
        conf = conf_models.ConferenceModel.objects.get(slug=kwargs['slug'])
        content['conf'] = sers.ConferenceSerializer(conf).data

        return Response(content, status=status.HTTP_200_OK)

    def patch(self, request, *args, **kwargs):
        conf = conf_models.ConferenceModel.objects.get(slug=kwargs['slug'])
        conf.name = request.data['data']['name']
        conf.brief = request.data['data']['brief']
        conf.slug = (request.data['data']['name']).replace(" ", "")
        conf.date_from = (request.data['data']['date_from']).split('T', 1)[0]
        conf.date_to = (request.data['data']['date_to']).split('T', 1)[0]
        conf.address = request.data['data']['address']
        conf.price.amount = request.data['data']['price']

        conf.save()
        return Response(status=status.HTTP_200_OK)

    def delete(self, request, *args, **kwargs):
        conf = conf_models.ConferenceModel.objects.get(name=request.data['data']['name'])
        conf.delete()

        return Response(status=status.HTTP_200_OK)

    def post(self, request, *args, **kwargs):
        logger.debug(request.data)
        request.data['data']['date_from'] = (request.data['data']['date_from']).split('T', 1)[0]
        request.data['data']['date_to'] = (request.data['data']['date_to']).split('T', 1)[0]

        org = u_models.OrganizationModel.objects.get(
            user__username=request.data['data']['organization']['user']['username'])

        object1 = conf_models.ConferenceModel(
            date_to=date.today(),
            date_from=date.today(),
            organization=org,
            price=request.data['data']['price'], address=request.data['data']['address'],
            name=request.data['data']['name'], slug=request.data['data']['slug'],
            brief=request.data['data']['brief'])

        object1.save()

        return Response(status=status.HTTP_201_CREATED)


class DisplayConferenceView(generic.ListView):
    model = conf_models.ConferenceModel
    template_name = 'conferences/display_conferences.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        conferences = self.conf_list()
        context['upcoming_confs'] = conferences.filter(date_from__gte=timezone.now()).order_by('date_from')
        context['past_confs'] = conferences.filter(date_from__lt=timezone.now()).order_by('-date_from')
        return context

    def conf_list(self):
        user = self.request.user
        if user.is_researcher:
            return ConferenceModel.objects.filter(visitors__username=user.username)
        if user.is_organization:
            return ConferenceModel.objects.filter(organization__user__username=user.username)


class CreateConferenceView(PermissionRequiredMixin, generic.CreateView):
    model = conf_models.ConferenceModel
    form_class = conf_forms.CreateConferenceForm
    template_name = 'conferences/create_conference.html'
    # permission_required = ('users.user.organization',)
    login_url = reverse_lazy('users:login-page')
    permission_denied_message = MessageMixin.messages.CONFERENCES.fail.create

    def has_permission(self):
        return self.request.user.is_organization

    def form_valid(self, form):
        username = self.kwargs.get('username')
        conf = form.save(username)
        return redirect('conferences:conf_display-page', username)

    def form_invalid(self, form):
        return super().form_invalid(form)


class ModifyConferenceMixin:
    def has_permission(self):
        conference_slug = self.request.get_full_path().split('/')[-1]
        conference = ConferenceModel.objects.get(slug=conference_slug)
        assert conference is not None
        logger.debug(f'`{conference}` is not None if user has permissions')
        can_edit = self.request.user.is_organization
        can_edit = can_edit and (conference is not None)
        can_edit = can_edit and self.request.user == conference.organization.user

        return can_edit


class EditConferenceView(ModifyConferenceMixin, PermissionRequiredMixin, LoginRequiredMixin, generic.UpdateView):
    model = conf_models.ConferenceModel
    form_class = conf_forms.EditConferenceForm
    template_name = 'conferences/edit_conference.html'
    # permission_required = ('users.organization', )
    login_url = reverse_lazy('users:login-page')

templates/conferences/conference_info.html
<!-- author: Khrystsiuk Dziyana -->

{% extends 'base.html' %}
{% load static %}
{% load djmoney %}
{% block content %}

    <div style=" background-color: orange">

        {#        <div class="btn_horizontal" style="position: absolute; top: 0;">#}
        {#            {% if user.is_organization %}#}
        {#            TODO 51: add path how we got here#}
        {#            TODO 52: change the button to the appropriate one#}
        {#                <div class="btn1_wide" href="{% url 'conferences:conf_display-page' user.username %}">Back</div>#}
        {#            {% endif %}#}
        {#        </div>#}

        <div class="content-section row justify-content-between">

            <div class="col-6">
                <h1 class="account-heading">{{ object.name }}</h1>

                <fieldset>
                    <p class="text-secondary">{{ object.date_from|date:"D, d M, Y" }} -
                        {{ object.date_to|date:"D, d M, Y" }}</p>
                    <p class="text-secondary">Address: {{ object.address }}</p>
                    <p class="text-secondary">Price: {% money_localize object.price %}</p>
                </fieldset>

                <div>
                    <h2>Events</h2>
                    <ul>
                        {% for event in object.events_list %}
                            <li>
                                <a href="{% url 'conferences:event_detail-page' object.slug event.event_id %}">{{ event }} </a>
                            </li>
                            {% empty %}
                            <a>There are no events added to this conference yet.</a>
                        {% endfor %}
                    </ul>
                </div>
                {% if user.id == object.organization.user_id %}
                    <div class="dropdown">

                            <button class="btn1_wide" type="button" id="dropdownMenuButton"
                                    data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                +
                            </button>
                            <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                                <a class="dropdown-item"
                                   href="{% url 'conferences:event_create-page' object.slug user.username %}?type=lunch">Lunch</a>
                                <a class="dropdown-item"
                                   href="{% url 'conferences:event_create-page' object.slug user.username %}?type=lecture">Lecture</a>
                            </div>
                    </div>
                {% endif %}
            </div>

            {% if user.is_researcher and user_participate %}
                <p><mark>You already have ticket for this conference.</mark></p>
           {% elif not user.is_active%}
                <h5><mark> <a class="viewlink" href="{% url 'users:login-page' %}"> <strong>Log in</strong> </a>  to buy a ticket.</mark></h5>
            {% endif %}



            <div class="dropdown col-1">
                {% if user.id == object.organization.user_id %}
                    <button class="btn bg-transparent" type="button" id="dropdownMenuButton"
                            data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"
                            style="font-size: 30px;">
                        &#8942
                    </button>
                    <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                        <a class="dropdown-item"
                           href="{% url 'conferences:conf_edit-page' user.username object.slug %}">Edit conference</a>
                        <!-- Button trigger modal -->
                        <button type="button" class="btn btn-primary dropdown-item" data-toggle="modal" data-target="#DeleteModal">
                          Delete
                        </button>

                    </div>
                {% endif %}
            </div>
        </div>

        {% if user.is_active and user.is_organization and user.organization == object.organization %}
            <!-- Modal -->
            <div class="modal" id="DeleteModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
              <div class="modal-dialog modal-dialog-centered" role="document">
                <div class="modal-content">
                  <div class="modal-header">
                    <h3 class="modal-title" id="exampleModalLongTitle">Delete conference</h3>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                      <span aria-hidden="true">&times;</span>
                    </button>
                  </div>
                  <div class="modal-body">
                    <form method="POST" action="{% url 'conferences:conf_delete-page' object.slug %}" novalidate>{% csrf_token %}
                        <h5> Are you sure you want to delete <strong>{{ object.name }}</strong> conference?</h5>
                        <button class="btn btn-primary" type="submit">Delete</button>
                    </form>
                  </div>
                </div>
              </div>
            </div>
        {% endif %}
          </div>
        </div>
    </div>

{% endblock %}

templates/conferences/delete_event.html
<!-- author: Khrystsiuk Dziyana -->

{% extends 'base.html' %}

{% block content %}
<div class="container pt-5">
    <form method="POST" novalidate>{% csrf_token %}
        <h3> Are you sure you want to delete {{ object.name }} event?</h3>
        <button class="btn btn-outline-info" type="submit">Delete</button>
        <a href="{% url 'conferences:event_detail-page' object.conference.slug object.event_id%}" class="btn btn-outline-info" >Cancel</a>
    </form>
</div>
{% endblock %}

templates/conferences/display_conferences.html
<!-- author: Khrystsiuk Dziyana -->

{% extends 'base.html' %}
{% block content %}
    <div>
        <ul style="list-style: none; position: relative;">
        <p>Future conferences</p>
            {% for conf in upcoming_confs %}
                <li>
                    <div onclick="location.href='{% url 'conferences:conf_detail-page' conf.slug %}';"
                         style="cursor: pointer;" class="content-section media-body hoverable_href">
                        <fieldset>
                            <p class="account-heading">{{ conf.name }}</p>
                            <p class="text-secondary">{{ conf.date_from|date:"D, d M, Y" }} -
                                {{ conf.date_to|date:"D, d M, Y" }}</p>
                            <p class="text-secondary">Address: {{ conf.address }}</p>
                        </fieldset>
                    </div>
                </li>

                {% empty %}
                <hr>There are no conferences planed for future ;(
            {% endfor %}
        </ul>
        {% if past_confs %}
            <ul style="list-style: none; position: relative;">
            <p>Past conferences</p>
            {% for conf in past_confs %}
                <li>
                    <div onclick="location.href='{% url 'conferences:conf_detail-page' conf.slug %}';"
                         style="cursor: pointer;" class="content-section media-body hoverable_href">
                        <fieldset>
                            <p class="account-heading">{{ conf.name }}</p>
                            <p class="text-secondary">{{ conf.date_from|date:"D, d M, Y" }} -
                                {{ conf.date_to|date:"D, d M, Y" }}</p>
                            <p class="text-secondary">Address: {{ conf.address }}</p>
                        </fieldset>
                    </div>
                </li>
            {% endfor %}
        </ul>
        {% endif %}
    {% if user.is_organization %}
        <div class="btn_horizontal">
            <a class="btn1_wide" href="{% url 'conferences:conf_create-page' user.username %}">Create a new conference
            </a>
        </div>
    {% elif user.is_researcher %}
        <div class="btn_horizontal">
            <a class="btn1_wide" href="{% url 'ch:search-page' %}?type=conferences">Browse other conferences
            </a>
        </div>
    {% endif %}
    </div>
{% endblock content %}

templates/conferences/edit_conference.html
<!-- author: Khrystsiuk Dziyana -->

{% extends 'base.html' %}

{% load static %}
{% load crispy_forms_tags %}

{% block content %}
<div class="row">
	<div class="col-md-8 col-sm-10 col-12">
		<h4>Edit {{ object.name }} conference</h4>
		<form method="POST" enctype="multipart/form-data" name="conf_form">{% csrf_token %}
			<input type="hidden" name="next" value="{{ next }}">
			{{ form|crispy }}
			<button class="btn btn-outline-info" type="submit">Save changes</button>
            <a href="{% url 'conferences:conf_detail-page' object.slug%}" class="btn btn-outline-info" >Cancel</a>
		</form>
	</div>
</div>
    <script src="{% static 'js/conf_form.js' %}"></script>
{% endblock %}

templates/conferences/event_info.html
<!-- author: Khrystsiuk Dziyana -->

{% extends 'base.html' %}
{% load static %}
{% load djmoney %}

{% block content %}
    <button style="position:absolute; top:170px; right:250px;" class="btn btn-info" onclick="location.href='{% url 'conferences:conf_detail-page' object.conference.slug %}';">
    Back to conference detail
    </button>
<h1>{{object.name}}</h1>
<h4><strong>Location:</strong> {{object.location}}</h4>
<h5><strong>Start:</strong> {{ object.date_time }}</h5>
<h5><strong>Duration:</strong> {{ object.duration }}</h5>
    {% if object.type == 'lunch' %}
        <p style="white-space: pre-wrap; word-wrap: break-word;"><strong>Menu:</strong> <br>{{ object.lunch.menu |safe }}</p>
        <p>Price: {% money_localize object.lunch.price %}</p>
    {% endif %}
<p style="white-space: pre-wrap; word-wrap: break-word;"><strong>Description:</strong> <br>{% if object.description %}{{ object.description |safe }}{% else %}No description available{% endif %}</p>

<div>
    {% if user.id == object.conference.organization.user_id%}
        <a class="btn btn-sm btn-info" href="{% url 'conferences:event_edit-page' object.conference.slug user.username object.event_id %}">Edit event</a>
        <a class="btn btn-sm btn-info" href="{% url 'conferences:event_delete-page' object.conference.slug user.username object.event_id%}">Delete event</a>
    {%  endif %}
</div>
<br>
{% if object.lecture.researchers.all %}
    <h4>Researchers:</h4>
    {% if user == object.conference.organization.user %}
    <menu>
        {% for res in object.lecture.researchers.all %}
            <li>
            <div style="display:flex; flex-direction: row;">
                <h5>{{ res }}</h5>
                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                <h6 class="{% if res.approved %}btn-outline-success{% else %}btn-outline-danger{% endif %}" >Approved: {{ res.approved }}</h6>
            </div>
            </li>
        {% endfor %}
    </menu>

    {% else  %}
    <menu>
        {% for res in object.lecture.researchers.all %}

            {% if res.approved %}
                <li>
                <h5>{{ res }}</h5>
                </li>
            {% endif %}

        {% endfor %}
    </menu>
    {% endif %}
{% endif %}

{% endblock %}

templates/conferences/my_lectures.html
<!-- author: Khrystsiuk Dziyana -->

{% extends 'base.html' %}
{% block content %}
    <div>
        <ul style="list-style: none; position: relative;">
        <h4>My lectures</h4>
            {% for lecture in user_events %}
                <li>
                    <div onclick="location.href='{% url 'conferences:event_detail-page' lecture.conference.slug lecture.event_id%}';"
                         style="cursor: pointer;" class="content-section media-body hoverable_href">
                        <fieldset>
                            <p class="account-heading">{{ lecture.name }}</p>
                            <p class="text-secondary">{{ lecture.date_time|date:"Y-m-d G:i" }}, duration:
                                {{ lecture.duration }}</p>
                            <p class="text-secondary">Location: {{ lecture.location }}</p>
                            <p class="text-secondary"><a href="{% url 'conferences:conf_detail-page' lecture.conference.slug %}">Conference detail</a></p>
                        </fieldset>
                    </div>
                </li>

                {% empty %}
                <hr>You don't have any lectures planed yet ;)
            {% endfor %}
        </ul>
    </div>
{% endblock content %}