ch/urls.py
# author: Shchapaniak Andrei

from django.urls import path

import ch.views as views

app_name = 'ch'

urlpatterns = [
    path('', views.IndexView.as_view(), name='home-page'),
    path('api/get_conf_state/<slug:slug>', views.PurchaseGetState.as_view(), name='api_get-conf-state-slug'),
    path('api/refund_money/<slug:slug>', views.PurchaseRefundMoney.as_view(), name='api_get-refund-money-slug'),
    path('api/get_all_states_bucket', views.PurchaseGetStateConfsUser.as_view(), name='api_get-all-states-bucket'),
    path('api/change_capacity_bucket/<slug:slug>', views.PurchaseManipulateBucket.as_view(), name='api_change-capacity-bucket-slug'),
    path('api/buy_confs', views.PurchaseBuyConfs.as_view(), name='api_buy-confs'),
    path('search', views.SearchView.as_view(), name='search-page'),
    path('<slug>/bucket', views.PurchasesView.as_view(), name='bucket-page'),
]

conference_hub/urls.py
# author: Shchapaniak Andrei

from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views

from rest_framework_simplejwt.views import (
    TokenRefreshView,
)


urlpatterns = [
    path('admin/', admin.site.urls),

    path('api/', views.getRoutes),
    path('api/token/', views.MyTokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),

    # path('', include('ch.urls')),
    path('users/', include('users.urls')),
    path('conferences/', include('conferences.urls')),
    path('ch/', include('ch.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'conference_hub.views.error_404_view'

conferences/urls.py
# author: Shchapaniak Andrei
# author: Khrystsiuk Dziyana

from django.urls import path
from conferences import views

from rest_framework import routers

app_name = 'conferences'

urlpatterns = [
    path('', views.ConferencesListView.as_view(), name='conferences-page'),
    path('api/get_conf/<slug:slug>', views.ConferenceGetOneAPI.as_view(), name='api_get-one-conf'),
    path('api/get_all_confs', views.ConferenceGetAllAPI.as_view(), name='api_get-all-confs'),
    path('api/manipulate_conf/<slug:slug>', views.ConferenceOrganizationManipulateAPI.as_view(), name='api_manipulate-conf'),
    path('api/get_events/<slug:slug>', views.ConferenceGetEventsAPI.as_view(), name='api_get_events-conf'),
    path('api/create_event/<slug:slug>', views.ConferenceCreateEventAPI.as_view(), name='api_create_event-conf'),
    path('api/delete_event/<slug:slug>', views.ConferenceDeleteEventAPI.as_view(), name='api_delete_event-conf'),
    path('api/update_event/<slug:slug>', views.ConferenceUpdateEventAPI.as_view(), name='api_update_event-conf'),

    path('<slug:username>/display', views.DisplayConferenceView.as_view(), name='conf_display-page'),
    path('<slug:username>/my_lectures', views.UserEventsView.as_view(), name='user_lectures-page'),
    path('<slug:username>/create', views.CreateConferenceView.as_view(), name='conf_create-page'),
    path('<slug:username>/edit/<slug:slug>', views.EditConferenceView.as_view(), name='conf_edit-page'),
    path('delete/<slug:slug>', views.DeleteConferenceView.as_view(), name='conf_delete-page'),
    path('<slug:slug>', views.ConferenceInfoView.as_view(), name='conf_detail-page'),
    path('<slug:slug>/event/<slug:username>/create', views.CreateEventView.as_view(), name='event_create-page'),
    path('<slug:slug>/event/<slug:username>/edit/<int:pk>', views.EditEventView.as_view(), name='event_edit-page'),
    path('<slug:slug>/event/<slug:username>/delete/<int:pk>', views.DeleteEventView.as_view(), name='event_delete-page'),
    path('<slug:slug>/event/<int:pk>', views.EventInfoView.as_view(), name='event_detail-page'),
]

users/urls.py
# author: Shchapaniak Andrei
# author: Skuratovich Aliaksandr

from django.contrib.auth import views as auth_views
from django.urls import path, include
from users import views

from rest_framework import routers

router = routers.DefaultRouter()
router.register(r'users_list', views.ConferenceUserListAPIView, 'api_users-list')
router.register(r'signup-researcher', views.ResearcherSignupAPIView, 'api_signup-researcher')
router.register(r'signup-organization', views.OrganizationSignupAPIView, 'api_signup-organization')
router.register('', views.ProfileAPIView, 'api_profile')

app_name = 'users'

urlpatterns = [
    # path('', views.ConferenceUserListView.as_view(), name='users-models'),  # move to routers
    path('api/get_users_all', views.ConferenceUserGetUsers.as_view(), name='api_get-users-all'),
    path('api/get_users_researchers', views.ConferenceUserGetResearchers.as_view(), name='api_get-users-researchers'),
    path('api/get_users_organizations', views.ConferenceUserGetOrganizations.as_view(), name='api_get-users-organizations'),
    path('api/manipulate_info_user', views.ConferenceUserGetInfo.as_view(), name='api_get-info-user'),
    path('api/login', views.ConferenceUserSigninAPIView.as_view(), name='api-login-view'),
    path('api/get_invite_context', views.InviteAPIView.as_view(), name='api-invite-view'),
    path('api/', include(router.urls)),  # move to routers

    path('invites', views.InviteView.as_view(), name='invites-page'),
    path('login', views.ConferenceUserSigninView.as_view(), name='login-page'),
    path('logout', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout-page'),

    path('signup', views.ConferenceUserSignupView.as_view(), name='signup-page'),

    path('signup/researcher', views.ResearcherSignupView.as_view(), name='signup_researcher-page'),
    path('signup/organization', views.OrganizationSignupView.as_view(), name='signup_organization-page'),

    path('<slug>/edit_profile', views.ProfileUpdateView.as_view(), name='profile_update-page'),
    path('<slug>/password_change', views.ProfileChangePasswordView.as_view(), name='password_change-page'),
    path('<slug>/account_delete', views.AccountDeleteView.as_view(), name='account_delete-page'),

    path('<slug>/organizations', views.OrganizationsView.as_view(), name='organizations-page'),
    path('<slug>/employees', views.EmployeesView.as_view(), name='employees-page'),

    path('<slug>', views.ProfileView.as_view(), name='profile-page'),
]

users/forms/organization.py
# author: Skuratovich Aliaksandr

from users.forms import ConferenceUserSignupForm
from users.models import OrganizationModel, ConferenceUserModel
from django.db import transaction
from django import forms


class OrganizationUpdateForm(forms.ModelForm):

    class Meta:
        model = OrganizationModel
        fields = []


class OrganizationSignupForm(ConferenceUserSignupForm):

    # TODO 14: change html from 'name' to 'Company name',
    class Meta(ConferenceUserSignupForm):
        model = ConferenceUserModel
        fields = ('email', 'username', 'name', 'country', 'city', 'password1', 'password2')

    @transaction.atomic
    def save(self, commit=True):
        user = super().save(commit=False)
        user.is_organization = True
        user.save()
        organization = OrganizationModel.objects.create(user=user)
        return user

users/forms/profile.py
# author: Skuratovich Aliaksandr

from users.models import ProfileModel
from django import forms


# TODO 8: add different forms for different types of users (move them to appropriate files)

class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = ProfileModel
        fields = ('image', )

users/views/conferenceuser.py
# author: Skuratovich Aliaksandr
# author: Shchapaniak Andrei

from django.contrib.messages.views import SuccessMessageMixin
from conference_hub.utils.message_wrapper import MessageMixin
from django.views.generic.base import TemplateView
from users.forms import ConferenceUserSigninForm, ConferenceUserSignupForm
from django.contrib.auth import logout, views, get_user_model, authenticate
from users import models as u_models
from django.views import generic
from django.views import View

from rest_framework import viewsets, generics, authentication
from users import serializers as sers
from rest_framework import serializers

from rest_framework import exceptions
from rest_framework.response import Response
from rest_framework.views import APIView
from rest_framework.authentication import SessionAuthentication, TokenAuthentication
from rest_framework.permissions import IsAuthenticated, AllowAny
from rest_framework import status

import logging

logger = logging.getLogger(__name__)


class ConferenceUserGetUsers(APIView):
    queryset = u_models.ConferenceUserModel
    serializer_class = sers.ConferenceUserSerializer

    def get(self, request, *args, **kwargs):
        users = u_models.ConferenceUserModel.objects.all()

        content = {}
        res = []
        for user in users:
            if user.is_researcher:
                res.append(sers.ResearcherInfoSerializer(user.researcher).data)
            elif user.is_organization:
                res.append(sers.OrganizationInfoSerializer(user.organization).data)

        content["users"] = res

        return Response(content, status=status.HTTP_200_OK)

class ConferenceUserGetResearchers(APIView):
    queryset = u_models.ResearcherModel
    serializer_class = sers.ResearcherInfoSerializer

    def get(self, request, *args, **kwargs):
        users = u_models.ConferenceUserModel.objects.all()

        content = {}
        arr_res = []
        for user in users:
            if user.is_researcher:
                arr_res.append(sers.ResearcherInfoSerializer(user.researcher).data)

        content["users"] = arr_res
        return Response(content, status=status.HTTP_200_OK)

class ConferenceUserGetOrganizations(APIView):
    queryset = u_models.OrganizationModel
    serializer_class = sers.OrganizationInfoSerializer

    def get(self, request, *args, **kwargs):
        users = u_models.ConferenceUserModel.objects.all()

        content = {}
        arr_org = []
        for user in users:
            if user.is_researcher:
                arr_org.append(sers.ResearcherInfoSerializer(user.researcher).data)

        content["users"] = arr_org
        return Response(content, status=status.HTTP_200_OK)


class ConferenceUserGetInfo(generics.RetrieveUpdateDestroyAPIView):
    queryset = u_models.ConferenceUserModel.objects.all()
    serializer_class = sers.ResearcherInfoSerializer
    permission_classes = (IsAuthenticated, )

    def get(self, request, *args, **kwargs):
        user = u_models.ConferenceUserModel.objects.get(username=request.user.username)

        content = {}
        if user.is_researcher:
            content["infouser"] = sers.ResearcherInfoSerializer(user.researcher).data
        elif user.is_organization:
            content["infouser"] = sers.OrganizationInfoSerializer(user.organization).data

        return Response(content, status=status.HTTP_200_OK)

    def patch(self, request, *args, **kwargs):
        user = u_models.ConferenceUserModel.objects.get(username=request.user.username)

        user.name = request.data['data']['user']['name']
        user.email = request.data['data']['user']['email']
        user.username = request.data['data']['user']['username']
        user.city = request.data['data']['user']['city']
        user.country = request.data['data']['user']['country']

        if user.is_researcher:
            user.researcher.last_name = request.data['data']['last_name']
            user.researcher.save()

        user.save()

        return Response(status=status.HTTP_200_OK)



class ConferenceUserSignupView(TemplateView):
    template_name = 'users/signup.html'


class ConferenceUserLogoutView(View, SuccessMessageMixin):
    success_message = MessageMixin.messages.USERS.success.logout

    def get(self, request):
        logout(request)


class ConferenceUserSigninView(views.LoginView, SuccessMessageMixin):
    success_message = MessageMixin.messages.USERS.success.login
    template_name = 'users/login.html'
    form = ConferenceUserSigninForm


class ConferenceUserListView(generic.ListView):
    model = u_models.ConferenceUserModel
    template_name = 'users/users.html'


class ConferenceUserListAPIView(viewsets.ReadOnlyModelViewSet):
    serializer_class = sers.ConferenceUserSerializer
    queryset = u_models.ConferenceUserModel.objects.all()


class SignupAPIViewMixin(viewsets.ViewSetMixin, generics.CreateAPIView):
    permission_classes = (AllowAny, )
    serializer_class = None

    def post(self, request, *args, **kwargs):
        logger.debug('request %s ' % request)
        return super().post(request, *args, **kwargs)


class ResearcherSignupAPIView(SignupAPIViewMixin):
    queryset = u_models.ResearcherModel.objects.all()
    serializer_class = sers.RegisterResearcherSerializer


class OrganizationSignupAPIView(viewsets.ViewSetMixin, generics.CreateAPIView):
    queryset = u_models.OrganizationModel.objects.all()
    serializer_class = sers.RegisterOrganizationSerializer


class Auth(authentication.BaseAuthentication):
    def authenticate(self, request):
        # Get the username and password
        username = request.data.get('username', None)
        password = request.data.get('password', None)
        if not username or not password:
            raise exceptions.AuthenticationFailed('No credentials provided.')
        credentials = {
            get_user_model().USERNAME_FIELD: username,
            'password': password
        }
        user = authenticate(**credentials)
        if user is None:
            raise exceptions.AuthenticationFailed('Invalid username/password.')
        if not user.is_active:
            raise exceptions.AuthenticationFailed('User inactive or deleted.')
        return (user, None)  # authentication successful


class ConferenceUserSigninAPIView(APIView):
    authentication_classes = (SessionAuthentication, Auth)
    permission_classes = (IsAuthenticated, )

    def post(self, request, format=None):
        content = {
            "user": sers.ConferenceUserSerializer(request.user).data,
        }

        return Response(content, status=status.HTTP_200_OK)

users/views/organization.py
# author: Skuratovich Aliaksandr

from users.models import ConferenceUserModel, OrganizationEmployeeModel
from conference_hub.utils.message_wrapper import MessageMixin
from django.http import JsonResponse, HttpResponseBadRequest
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.edit import CreateView
from users.forms import OrganizationSignupForm
from django.contrib.auth import login
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.contrib import messages
from django.views import generic
from django.db.models import Q
from django.http import Http404
from datetime import datetime

import json
import logging

logger = logging.getLogger(__name__)


class OrganizationSignupView(CreateView):
    model = ConferenceUserModel
    form_class = OrganizationSignupForm
    template_name = 'users/signup_form.html'

    def get_context_data(self, **kwargs):
        kwargs['user_type'] = 'organization'
        return super().get_context_data(**kwargs)

    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        messages.success(self.request, MessageMixin.messages.USERS.success.signup)
        return redirect(user.get_absolute_url())

    def form_invalid(self, form):
        messages.error(self.request, MessageMixin.messages.USERS.fail.signup)
        return super().form_invalid(form)


# TODO: add permissions mixin
class EmployeesView(LoginRequiredMixin, generic.ListView):
    template_name = 'users/organizations_employees.html'
    username = None
    organization = None
    login_url = reverse_lazy('users:login-page')

    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_authenticated or not request.user.is_organization:
            return self.handle_no_permission()
        return super().dispatch(request, *args, **kwargs)

    def get(self, request, *args, **kwargs):
        url = self.request.get_full_path()
        logger.debug(f'url: {url}')
        self.username = url.split('/')[-2]
        logger.debug(f'org username: {self.username}')
        self.organization = ConferenceUserModel.objects.get(username=self.username)
        if not self.organization.is_organization:
            raise Http404("Provided user is not an organization")
        logger.debug(f'organization: {self.organization}')
        return super().get(request, *args, **kwargs)

    def get_queryset(self):
        employees = OrganizationEmployeeModel.objects.filter(
            organization__user=self.organization, approved=True, rejected=False, finished=False
        )
        return employees

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(object_list=object_list, **kwargs)
        context['url_user'] = self.organization
        return context

    def post(self, request, *args, **kwargs):
        is_ajax = request.headers.get('X-Requested-With') == 'XMLHttpRequest'
        if is_ajax:
            data = json.load(request)
            user = request.user
            logger.debug(f'organization: {user}; id__in: {data}')
            jobs_to_delete = OrganizationEmployeeModel.objects.filter(
                Q(organization__user=user, id__in=data)
            ).distinct()
            logger.debug(f'jobs to delete: {len(jobs_to_delete)}')
            for org in jobs_to_delete:
                logger.debug(f'{org} finished')
                org.date_fired = datetime.now()
                org.finished = True
                org.save()
            return JsonResponse({})
        else:
            return HttpResponseBadRequest('Invalid Request')

templates/users/login.html
<!-- author: Skuratovich Aliaksandr -->

{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section">
        <form method="POST">{% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Log In</legend>
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn1_wide" type="submit">Log In</button>
            </div>
        </form>
        <div class="border-top pt-3">
            <small class="text-muted">
                Do you need an account?<a class="ml-2" href="{% url 'users:signup-page' %}">Sign Up Now</a>
            </small>
        </div>
    </div>
{% endblock content %}

templates/users/logout.html
<!-- author: Skuratovich Aliaksandr -->

{% extends 'base.html' %}
{% load static %}
{% block content %}
    <div class="content-section" style="text-align: center">
        <h2>You have been logged out</h2>
        <div class="border-top pt-3">
            <small class="text-muted">
                Want to stay online?<a class="ml-2" href="{% url 'users:login-page' %}">Log In Again</a>
            </small>
        </div>
    </div>
{% endblock content %}

templates/users/profile.html
<!-- author: Skuratovich Aliaksandr -->

{% extends "base.html" %}
{% block title %}Profile Page{% endblock title %}
{% block content %}

    {# TODO 19 add styles #}
    <div class="content-section row justify-content-between">
        <div class="col-4">
            <div class="media">
                <img class="rounded-circle account-img" src=" {{ object.profile.image.url }} ">
            </div>

            {% if object.address %}
                <p class="text-secondary"><b>Address:</b> {{ object.address }}</p>
            {% endif %}

        </div> <!-- col-4 -->

        {% if not object.is_superuser %}

        <div class="col-6">

            <fieldset>
                {% if object.is_researcher %}
                    <p class="account-heading">{{ object.name }} {{ object.researcher.last_name }}</p>
                {% elif object.is_organization %}
                    <p class="account-heading">{{ object.name }}</p>
                {% endif %}
                <p class="text-secondary">{{ object.username }}</p>
                <p class="text-secondary"><b>Email:</b> {{ object.email }}</p>
            </fieldset>

            {% if object.is_researcher and organizations.count > 0 %}
                <div>
                    <a href="{{ object.get_absolute_url }}/organizations"><h2>Organizations</h2></a>
                </div>
                <ul>
                    {% for org in organizations %}
                        <li>
                            <a href="{{ request.site.name }}/users/{{ org.organization.user.username }}">
                                {{ org.organization.user.name }}
                            </a>
                        </li>
                    {% endfor %}
                </ul>
            {% endif %}
{#            {% if object.is_organization %}#}
{#                <div>#}
{#                    <h2>Researchers</h2>#}
{#                </div>#}
{#                <div>#}
{#                    <h2>Conferences</h2>#}
{#                </div>#}
{#            {% elif object.is_researcher %}#}
{#                <div>#}
{#                    <h2>Lectures</h2>#}
{#                </div>#}
{#                <div>#}
{#                    <h2>Poster Sessions</h2>#}
{#                </div>#}
{#            {% else %}#}
{#            {% endif %}#}
        </div> <!-- col-6 -->

        {#Dropdown button - edit, change password, delete#}
        <div class="col-1">
            {% if user.is_authenticated and object == user %}
                <button class="btn bg-transparent" type="button" id="dropdownMenuButton"
                        data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"
                        style="font-size: 30px;">
                    &#8942
                </button>
                <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                    <a class="dropdown-item" href="{% url 'users:profile_update-page' user.username %}">Edit
                        profile</a>
                    <a class="dropdown-item" href="{% url 'users:password_change-page' user.username %}">Change
                        password</a>
                    <!-- Button trigger modal -->
                    <button type="button" class="dropdown-item evil-and-danger" data-toggle="modal" data-target="#modalUserDelete">
                      Delete account
                    </button>
                </div>
            {% endif %}
        </div>
        <!-- Modal -->
        <div class="modal" id="modalUserDelete" tabindex="-1" role="dialog" aria-labelledby="modalUserDeleteTitle" aria-hidden="true">
          <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
              <div class="modal-header">
                <h3 class="modal-title" id="modalUserDeleteLongTitle">Delete account</h3>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
              </div>
              <div class="modal-body">
                <form method="POST" action="{% url 'users:account_delete-page' user.username %}" novalidate>{% csrf_token %}
                    <h5> Are you sure? This action will <strong>permanently</strong> delete your account.</h5>
                    <button class="btn btn-danger" type="submit">Delete</button>
                </form>
              </div>
            </div>
          </div>
        </div>

        {% endif %}
    </div>

{% endblock content %}

templates/users/profile_password_change.html
<!-- author: Skuratovich Aliaksandr -->

{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block title %}Change Password{% endblock title %}
{% block content %}

    <div class="content-section">

        <div class="form-group">
            <form method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                <fieldset class="form-group">
                    <legend class="border-bottom mb-4">Change password</legend>
                    {{ form|crispy }}
                </fieldset>

                <div class="form-group">
                    <button class="btn-outline-info" type="submit">Change Password</button>
                </div>
            </form>
            <a class="btn btn-sm btn-info" href="{% url 'users:profile-page' user.username %}">Back</a>

        </div>
    </div>
{% endblock content %}

templates/users/profile_update.html
<!-- author: Skuratovich Aliaksandr -->

{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block title %}Update profile{% endblock title %}
{% block content %}

    <div class="content-section">
        <form method="POST" enctype="multipart/form-data">
            <div class="row">
                <div class="col-6">
                    <div class="form-group">
                        {% csrf_token %}
                        <fieldset class="form-group">
                            <legend class="border-bottom mb-4">Edit profile</legend>
                            {{ u_form|crispy }}
                            {{ ro_form|crispy }}
                            {{ p_form|crispy }}
                        </fieldset>
                    </div>
                </div>
                <div class="col-6">
                </div>
            </div>
            <div class="form-group">
                <button class="btn1_wide center-text" type="submit">Save</button>
            </div>

            <a class="btn1_wide center-text" style="background: rgba(140,140,140,0.6)"
               href="{% url 'users:profile-page' user.username %}">Back</a>
        </form>
    </div>
{% endblock content %}

templates/users/purchase.html
<!-- author: Shchapaniak Andrei -->

{% extends "base.html" %}
{% load static %}
{% load compress %}
{% block title %}Purchase Page{% endblock title %}

{% block content %}
    {% compress css %}
        <link rel="stylesheet" type="text/x-scss" href="{% static 'css/ch/style.scss' %}">
    {% endcompress %}

    {% if purchases %}
        {% for pur in purchases %}
            <li style="list-style-type:none;">
                <div class="content-section">
                    <div class="media">
                        <div class="media-body">
                            <a href="{% url 'conferences:conf_detail-page' pur.conference.slug %}"><p class="account-heading">{{ pur.conference.name }}</p></a>
                            <div style="display: flex;  justify-content: space-between;">
                                <div>
                                <p class="text-secondary">{{ pur.conference.date_from|date:"D, d M, Y" }} - {{ pur.conference.date_to|date:"D, d M, Y" }}</p>
                                <p class="text-secondary">Address: {{ pur.conference.address }}</p>
                                <p class="text-secondary">Prcie: {{ pur.conference.price }}</p>
                                </div>
                                <input type="checkbox" id="{{ pur.conference.id }}" onclick="change_price(event)" checked/>
                            </div>
                            <input type="hidden" id='{{ pur.conference.id }}__price' name="custId"
                                   value="{{ pur.conference.price.amount }}">
                            <button type="button" class="btn btn-primary"
                                    onclick="delete_from_the_bucket('{{ pur.conference.id }}')">Remove from bucket</button>
                        </div>
                    </div>
                </div>
            </li>
        {% endfor %}
        <div>
            <span style="display: inline-flex;">
                <p>€</p> &nbsp;
                <p id="finish_price">{{ sum.amount }}</p>
            </span>
            <br>
            <button type="button" class="btn btn-success" onclick="buy_tickets_to_conferences()">Buy</button>
        </div>
    {% else %}
        <li class="content-section empty-list center-text">Nothing found</li>
    {% endif %}


    <script>
        function change_price(e) {
            let id_el = e.target.getAttribute('id');
            let price_el = parseFloat(document.getElementById(id_el + "__price").getAttribute('value'));
            let finish_price = parseFloat(document.getElementById("finish_price").innerText)
            let state_box = document.getElementById(id_el).checked

            if (state_box === true) {
                document.getElementById("finish_price").innerText = (finish_price + price_el).toFixed(2);
            } else if (state_box === false) {
                document.getElementById("finish_price").innerText = (finish_price - price_el).toFixed(2);
            }
        }

        function getCookie(name) {
            let cookieValue = null;
            if (document.cookie && document.cookie !== "") {
                const cookies = document.cookie.split(";");
                for (let i = 0; i < cookies.length; i++) {
                    const cookie = cookies[i].trim();
                    // Does this cookie string begin with the name we want?
                    if (cookie.substring(0, name.length + 1) === (name + "=")) {
                        cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                        break;
                    }
                }
            }
            return cookieValue;
        }

        function delete_from_the_bucket(confid) {
            $.ajax({
                type: 'post',
                headers: {
                    'X-Requested-With': 'XMLHttpRequest',
                    'X-CSRFToken': getCookie('csrftoken')
                },
                data: JSON.stringify({'confid': confid, 'action': 'delete'}),
                dataType: 'json',
                success: (data) => {
                    window.location.reload();
                }
            })
        }

        function buy_tickets_to_conferences() {
            let buy_confs = []
            for (conf_id of {{ purs_conf_id }}) {
                let state_box = document.getElementById(conf_id).checked
                if (state_box === true) {
                    buy_confs.push(conf_id)
                }
            }

            $.ajax({
                type: 'post',
                headers: {
                    'X-Requested-With': 'XMLHttpRequest',
                    'X-CSRFToken': getCookie('csrftoken')
                },
                data: JSON.stringify({'confs': buy_confs, 'action': 'buy'}),
                dataType: 'json',
                success: (data) => {
                    if (data['valid'] === 'false') {
                        alert("You do not have enough money")
                        return;
                    }

                    window.location.reload();
                }
            })
        }
    </script>
{% endblock content %}

templates/users/signup.html
<!-- author: Skuratovich Aliaksandr -->

{% extends 'base.html' %}
{% load static %}
{% block content %}
    <div class="content-section center-text">
        <h2>Sign Up</h2>
        <p class="lead">Select below the type of account you want to create</p>
        <div id="container">
            <a href="{% url 'users:signup_researcher-page' %}" class=btn1 role="button">I'm a researcher</a>
            <a href="{% url 'users:signup_organization-page' %}" class=btn1 role="button">I'm an organization</a>
        </div>
    </div>
{% endblock content %}